/*
    CREATE USER nombre_del_usuario
    IDENTIFIED BY "contraseña"
    DEFAULT TABLESPACE "USERS"
    TEMPORARY TABLESPACE "TEMP";
*/
CREATE USER ERICK
IDENTIFIED BY "123"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

GRANT ALL PRIVILEGES TO ERICK; --LE DAMOS LOS PRIVILEGIOS, ES IMPORTANTE!!!!